# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
use_modular_headers!

target 'PodfileExample' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for PodfileExample
    pod 'AFNetworking', :modular_headers => true

end
