source '@gitlib.zwcins.com/ios.library/sepc.git'# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
use_modular_headers!

plugin 'cocoapods-libs-config'
# 打繁体、付费包的时候，记得更改target
set_custom_options_for_libs_config :client => "cn", :target => "HuashengSecurities"

post_install do |installer|
  if installer.pods_project
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          if target.name=='HSHostManager'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) HSDefaultServer=@\"open\"'
          end
        end
      end
    end
  end
end

target 'PodfileExample' do
  pod 'Alamofire', '5.6.1-d'
  # Pods for PodfileExample
    pod 'AFNetworking', '4.0.1'

end

target 'Test2' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for PodfileExample
  pod 'AFNetworking', '4.0.0'
  
end
